files:
  - source: /package.nls.json
    translation: /package.nls.%two_letters_code%.json
  - source: /translations/bundle.l10n.json
    translation: /translations/bundle.l10n.%two_letters_code%.json
